
name = "UMG"
default_targets = ["win32", "win64"]
build_directory = "build_output"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
    "-*.md"
]



[appimage]
# custom appimage:
source_appimage = "build/love/linux64/love.AppImage"


shared_libraries = [
	"build/dlls/linux64/libsteam_api.so",
	"build/dlls/linux64/luasteam.so"
]



