
name: build_project


on:
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: python build/build.py

    - uses: actions/upload-artifact@v3
      with:
        name: game_build
        path: build_output/
