

name: build_project

on: push



jobs:
  darklua:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        path: main

    # Clone and build Darklua:
    - name: Clone Darklua
      uses: GuillaumeFalourd/clone-github-repo-action@v2.2
      with:
        depth: 1
        branch: 'main'
        owner: 'seaofvoices'
        repository: 'darklua'
    - name: Build Darklua
      run: |
        cd darklua
        cargo build --locked --release --target x86_64-unknown-linux-gnu
      env:
        CARGO_TARGET_DIR: output

    - name: Debug
      run: tree

    - name: Darklua Preprocessing
      run: |
        sudo chmod +x ./darklua/output/x86_64-unknown-linux-gnu/release/darklua
        sudo ./darklua/output/x86_64-unknown-linux-gnu/release/darklua process main main --config main/.darklua.json

    - name: Debug
      run: cat ./main/my_proj/my_file.lua



