

name: build_project

on: push



jobs:
  darklua:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        path: main

    - name: Clone Darklua
      uses: GuillaumeFalourd/clone-github-repo-action@v2.2
      with:
        depth: 1
        branch: 'main'
        owner: 'seaofvoices'
        repository: 'darklua'

    - name: Debug
      run: tree

    - name: Build Darklua
      run: |
        cd darklua
        cargo build --locked --release --target ubuntu-linux
      env:
        CARGO_TARGET_DIR: output

    - name: Debug
      run: tree

    - name: Darklua Preprocessing
      run: |
        sudo chmod +x ./darklua/output/release/ubuntu-linux/release/darklua
        sudo ./darklua/output/release/ubuntu-linux/release/darklua process main main --config main/.darklua.json

# location:
    # output/release/ubuntu-linux/release/darklua


    - name: Debug
      run: echo cat ./main/my_proj/my_file.lua



