


name: test_checkout


# on: workflow_dispatch
on: push



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        path: main

    - name: Checkout makelove
        # git+https://github.com/pfirsich/makelove.git@master
      run: pip3 install git+https://github.com/pfirsich/makelove.git@master

    - name: Debug0
      run: tree
    
    - name: Build
      run: cd main && python3 -m makelove win64

    - name: Debug
      run: tree

    - name: Artifact (Win64)
      uses: actions/upload-artifact@v2
      with:
        name: win64
        path: main/makelove-build/win64/

    - name: Cache
      uses: actions/cache/save@v3
      if: always()
      with:
        path: ./
        key: name

  call-workflow-passing-data:
    uses: ./.github/workflows/test_args.yml
    with:
      path: ./




