


name: test_checkout


# on: workflow_dispatch
on: push



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        path: main

    - name: Checkout makelove
      uses: actions/checkout@v2
      with:
        repository: pfirsich/makelove
        path: makelove

    - name: Debug0
      run: tree
    
    - name: Build
      run: cd main && python3 ../makelove/makelove win32

    - name: Debug
      run: tree

