

on:
  workflow_call:
    inputs:
      path: 
        required: true
        type: string

jobs:
  supertree:
    runs-on: ubuntu-latest

    steps:
    - name: Uncache
      uses: actions/cache@v2
      with:
        path: ./
        key: name

    - name: TREE
      run: tree ${{ inputs.path }}


