


name: test_checkout


# on: workflow_dispatch
on: push



jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with: 
        path: main

    - name: Checkout makelove
        # git+https://github.com/pfirsich/makelove.git@master
      run: pip3 install git+https://github.com/UntitledModGame/makelove.git@master

    - name: Debug0
      run: tree
    
    - name: Build
      run: cd main && python3 -m makelove win64 appimage

    - name: Debug
      run: tree

    - name: Artifact (Win64)
      uses: actions/upload-artifact@v2
      with:
        name: win64
        path: main/makelove-build/win64/


